// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currency.proto

package currency

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status1 "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// currencies is an enum which represents the allowed currencies for the API
type Currencies int32

const (
	Currencies_EUR Currencies = 0
	Currencies_USD Currencies = 1
	Currencies_JPY Currencies = 2
	Currencies_BGN Currencies = 3
	Currencies_CZK Currencies = 4
	Currencies_DKK Currencies = 5
	Currencies_GBP Currencies = 6
	Currencies_HUF Currencies = 7
	Currencies_PLN Currencies = 8
	Currencies_RON Currencies = 9
	Currencies_SEK Currencies = 10
	Currencies_CHF Currencies = 11
	Currencies_ISK Currencies = 12
	Currencies_NOK Currencies = 13
	Currencies_HRK Currencies = 14
	Currencies_RUB Currencies = 15
	Currencies_TRY Currencies = 16
	Currencies_AUD Currencies = 17
	Currencies_BRL Currencies = 18
	Currencies_CAD Currencies = 19
	Currencies_CNY Currencies = 20
	Currencies_HKD Currencies = 21
	Currencies_IDR Currencies = 22
	Currencies_ILS Currencies = 23
	Currencies_INR Currencies = 24
	Currencies_KRW Currencies = 25
	Currencies_MXN Currencies = 26
	Currencies_MYR Currencies = 27
	Currencies_NZD Currencies = 28
	Currencies_PHP Currencies = 29
	Currencies_SGD Currencies = 30
	Currencies_THB Currencies = 31
	Currencies_ZAR Currencies = 32
)

var Currencies_name = map[int32]string{
	0:  "EUR",
	1:  "USD",
	2:  "JPY",
	3:  "BGN",
	4:  "CZK",
	5:  "DKK",
	6:  "GBP",
	7:  "HUF",
	8:  "PLN",
	9:  "RON",
	10: "SEK",
	11: "CHF",
	12: "ISK",
	13: "NOK",
	14: "HRK",
	15: "RUB",
	16: "TRY",
	17: "AUD",
	18: "BRL",
	19: "CAD",
	20: "CNY",
	21: "HKD",
	22: "IDR",
	23: "ILS",
	24: "INR",
	25: "KRW",
	26: "MXN",
	27: "MYR",
	28: "NZD",
	29: "PHP",
	30: "SGD",
	31: "THB",
	32: "ZAR",
}

var Currencies_value = map[string]int32{
	"EUR": 0,
	"USD": 1,
	"JPY": 2,
	"BGN": 3,
	"CZK": 4,
	"DKK": 5,
	"GBP": 6,
	"HUF": 7,
	"PLN": 8,
	"RON": 9,
	"SEK": 10,
	"CHF": 11,
	"ISK": 12,
	"NOK": 13,
	"HRK": 14,
	"RUB": 15,
	"TRY": 16,
	"AUD": 17,
	"BRL": 18,
	"CAD": 19,
	"CNY": 20,
	"HKD": 21,
	"IDR": 22,
	"ILS": 23,
	"INR": 24,
	"KRW": 25,
	"MXN": 26,
	"MYR": 27,
	"NZD": 28,
	"PHP": 29,
	"SGD": 30,
	"THB": 31,
	"ZAR": 32,
}

func (x Currencies) String() string {
	return proto.EnumName(Currencies_name, int32(x))
}

func (Currencies) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{0}
}

// data store denoted by message keyword
type RateRequest struct {
	Base                 Currencies `protobuf:"varint,1,opt,name=Base,proto3,enum=Currencies" json:"Base,omitempty"`
	Destination          Currencies `protobuf:"varint,2,opt,name=Destination,proto3,enum=Currencies" json:"Destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RateRequest) Reset()         { *m = RateRequest{} }
func (m *RateRequest) String() string { return proto.CompactTextString(m) }
func (*RateRequest) ProtoMessage()    {}
func (*RateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{0}
}

func (m *RateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateRequest.Unmarshal(m, b)
}
func (m *RateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateRequest.Marshal(b, m, deterministic)
}
func (m *RateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateRequest.Merge(m, src)
}
func (m *RateRequest) XXX_Size() int {
	return xxx_messageInfo_RateRequest.Size(m)
}
func (m *RateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RateRequest proto.InternalMessageInfo

func (m *RateRequest) GetBase() Currencies {
	if m != nil {
		return m.Base
	}
	return Currencies_EUR
}

func (m *RateRequest) GetDestination() Currencies {
	if m != nil {
		return m.Destination
	}
	return Currencies_EUR
}

// same data store definition
type RateResponse struct {
	Base                 Currencies `protobuf:"varint,1,opt,name=Base,proto3,enum=Currencies" json:"Base,omitempty"`
	Destination          Currencies `protobuf:"varint,2,opt,name=Destination,proto3,enum=Currencies" json:"Destination,omitempty"`
	Rate                 float64    `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RateResponse) Reset()         { *m = RateResponse{} }
func (m *RateResponse) String() string { return proto.CompactTextString(m) }
func (*RateResponse) ProtoMessage()    {}
func (*RateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{1}
}

func (m *RateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateResponse.Unmarshal(m, b)
}
func (m *RateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateResponse.Marshal(b, m, deterministic)
}
func (m *RateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateResponse.Merge(m, src)
}
func (m *RateResponse) XXX_Size() int {
	return xxx_messageInfo_RateResponse.Size(m)
}
func (m *RateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RateResponse proto.InternalMessageInfo

func (m *RateResponse) GetBase() Currencies {
	if m != nil {
		return m.Base
	}
	return Currencies_EUR
}

func (m *RateResponse) GetDestination() Currencies {
	if m != nil {
		return m.Destination
	}
	return Currencies_EUR
}

func (m *RateResponse) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

// error handling
type StreamingRateResponse struct {
	// encapsulates one of two different message types (means any)
	//
	// Types that are valid to be assigned to Message:
	//	*StreamingRateResponse_RateResponse
	//	*StreamingRateResponse_Error
	Message              isStreamingRateResponse_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *StreamingRateResponse) Reset()         { *m = StreamingRateResponse{} }
func (m *StreamingRateResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingRateResponse) ProtoMessage()    {}
func (*StreamingRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{2}
}

func (m *StreamingRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRateResponse.Unmarshal(m, b)
}
func (m *StreamingRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRateResponse.Marshal(b, m, deterministic)
}
func (m *StreamingRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRateResponse.Merge(m, src)
}
func (m *StreamingRateResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingRateResponse.Size(m)
}
func (m *StreamingRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRateResponse proto.InternalMessageInfo

type isStreamingRateResponse_Message interface {
	isStreamingRateResponse_Message()
}

type StreamingRateResponse_RateResponse struct {
	RateResponse *RateResponse `protobuf:"bytes,1,opt,name=rate_response,json=rateResponse,proto3,oneof"`
}

type StreamingRateResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamingRateResponse_RateResponse) isStreamingRateResponse_Message() {}

func (*StreamingRateResponse_Error) isStreamingRateResponse_Message() {}

func (m *StreamingRateResponse) GetMessage() isStreamingRateResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *StreamingRateResponse) GetRateResponse() *RateResponse {
	if x, ok := m.GetMessage().(*StreamingRateResponse_RateResponse); ok {
		return x.RateResponse
	}
	return nil
}

func (m *StreamingRateResponse) GetError() *status.Status {
	if x, ok := m.GetMessage().(*StreamingRateResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamingRateResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamingRateResponse_RateResponse)(nil),
		(*StreamingRateResponse_Error)(nil),
	}
}

func init() {
	proto.RegisterEnum("Currencies", Currencies_name, Currencies_value)
	proto.RegisterType((*RateRequest)(nil), "RateRequest")
	proto.RegisterType((*RateResponse)(nil), "RateResponse")
	proto.RegisterType((*StreamingRateResponse)(nil), "StreamingRateResponse")
}

func init() { proto.RegisterFile("currency.proto", fileDescriptor_d3dc60ed002193ea) }

var fileDescriptor_d3dc60ed002193ea = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0xd3, 0x5d, 0x6f, 0x12, 0x4d,
	0x14, 0x07, 0x70, 0x16, 0x68, 0x69, 0x67, 0x81, 0xe7, 0x3c, 0xa3, 0x6d, 0x11, 0x5f, 0x4a, 0xb8,
	0x30, 0xa4, 0x89, 0x5b, 0x83, 0x5e, 0x79, 0xc7, 0x76, 0x5b, 0x56, 0x07, 0xb7, 0x64, 0xd6, 0x8d,
	0x42, 0x62, 0xcc, 0xb2, 0x99, 0x90, 0x4d, 0xec, 0x2e, 0xce, 0x0c, 0x17, 0xbd, 0xf7, 0x2b, 0xf9,
	0xfd, 0xcc, 0x39, 0xdb, 0x44, 0xaa, 0x5e, 0x7a, 0xf7, 0x0b, 0xe7, 0x85, 0x7f, 0x66, 0x66, 0x59,
	0x37, 0xdb, 0x6a, 0xad, 0x8a, 0xec, 0xd6, 0xdb, 0xe8, 0xd2, 0x96, 0xfd, 0x93, 0x75, 0x59, 0xae,
	0xbf, 0xaa, 0x73, 0xbd, 0xc9, 0xce, 0x8d, 0x4d, 0xed, 0xd6, 0x54, 0x85, 0xe1, 0x67, 0xe6, 0xca,
	0xd4, 0x2a, 0xa9, 0xbe, 0x6d, 0x95, 0xb1, 0xfc, 0x94, 0x35, 0xfd, 0xd4, 0xa8, 0x9e, 0x33, 0x70,
	0x46, 0xdd, 0xb1, 0xeb, 0x5d, 0x54, 0x6b, 0x72, 0x65, 0x24, 0x15, 0xf8, 0x0b, 0xe6, 0x06, 0xca,
	0xd8, 0xbc, 0x48, 0x6d, 0x5e, 0x16, 0xbd, 0xfa, 0x9f, 0x7d, 0xbb, 0xf5, 0xa1, 0x66, 0xed, 0x6a,
	0xbd, 0xd9, 0x94, 0x85, 0x51, 0xff, 0x7a, 0x3f, 0xe7, 0xac, 0xa9, 0x53, 0xab, 0x7a, 0x8d, 0x81,
	0x33, 0x72, 0x24, 0x79, 0xf8, 0xdd, 0x61, 0x47, 0xb1, 0xd5, 0x2a, 0xbd, 0xc9, 0x8b, 0xf5, 0xbd,
	0x7f, 0x7f, 0xcd, 0x3a, 0xd8, 0xf1, 0x45, 0xdf, 0xfd, 0x40, 0x31, 0xdc, 0x71, 0xc7, 0xdb, 0xed,
	0x0a, 0x6b, 0xb2, 0xad, 0x77, 0xa7, 0xce, 0xd8, 0x9e, 0xd2, 0xba, 0xd4, 0x14, 0xc6, 0x1d, 0x73,
	0xaf, 0x3a, 0x4b, 0x4f, 0x6f, 0x32, 0x2f, 0xa6, 0xb3, 0x0c, 0x6b, 0xb2, 0x6a, 0xf1, 0x0f, 0x59,
	0xeb, 0x46, 0x19, 0x93, 0xae, 0xd5, 0xd9, 0x8f, 0x3a, 0x63, 0xbf, 0x62, 0xf3, 0x16, 0x6b, 0x5c,
	0x26, 0x12, 0x6a, 0x88, 0x24, 0x0e, 0xc0, 0x41, 0xbc, 0x9b, 0x2f, 0xa0, 0x8e, 0xf0, 0xa7, 0x11,
	0x34, 0x10, 0x17, 0x4b, 0x01, 0x4d, 0x44, 0x20, 0x04, 0xec, 0x21, 0xa6, 0xfe, 0x1c, 0xf6, 0x11,
	0x61, 0x72, 0x05, 0x2d, 0xc4, 0x7c, 0x16, 0xc1, 0x01, 0x42, 0x5e, 0x47, 0x70, 0x88, 0x88, 0x2f,
	0x05, 0x30, 0x1a, 0x0f, 0xaf, 0xc0, 0x45, 0xbc, 0x8d, 0x05, 0xb4, 0x11, 0xd1, 0xb5, 0x80, 0x0e,
	0x8d, 0x4b, 0x01, 0x5d, 0x9a, 0x4a, 0x7c, 0xf8, 0x0f, 0xf1, 0x41, 0x2e, 0x00, 0x10, 0x93, 0x24,
	0x80, 0xff, 0x29, 0x86, 0x9c, 0x01, 0xa7, 0x3d, 0x93, 0x00, 0x1e, 0x10, 0xa2, 0x05, 0x3c, 0xa4,
	0x71, 0x11, 0xc0, 0x11, 0x6d, 0x0e, 0x24, 0x1c, 0x13, 0x66, 0x31, 0x9c, 0x10, 0x22, 0x09, 0x3d,
	0x84, 0x90, 0x1f, 0xe1, 0x11, 0xe2, 0xfd, 0xa7, 0x08, 0xfa, 0x84, 0x85, 0x84, 0xc7, 0x14, 0x63,
	0x19, 0xc0, 0x13, 0x0a, 0x1f, 0xce, 0xe1, 0x29, 0x65, 0x9e, 0x06, 0xf0, 0x8c, 0x62, 0x84, 0x3e,
	0x9c, 0x22, 0x96, 0x13, 0x09, 0x83, 0x71, 0xc1, 0x0e, 0xee, 0x8e, 0xed, 0x96, 0x3f, 0x67, 0xad,
	0xa9, 0xb2, 0x78, 0x3b, 0xbc, 0xed, 0xed, 0xbc, 0xd3, 0xfe, 0xfd, 0x2b, 0xe3, 0x6f, 0x58, 0x37,
	0xde, 0xae, 0x4c, 0xa6, 0xf3, 0x95, 0xc2, 0x82, 0xf9, 0xad, 0xfd, 0xd8, 0xfb, 0xeb, 0x83, 0x18,
	0x39, 0x2f, 0x9d, 0xd5, 0x3e, 0x7d, 0x08, 0xaf, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xba, 0xa2,
	0x6c, 0x22, 0x33, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CurrencyClient is the client API for Currency service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CurrencyClient interface {
	GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateResponse, error)
	SubscribeRates(ctx context.Context, opts ...grpc.CallOption) (Currency_SubscribeRatesClient, error)
}

type currencyClient struct {
	cc *grpc.ClientConn
}

func NewCurrencyClient(cc *grpc.ClientConn) CurrencyClient {
	return &currencyClient{cc}
}

func (c *currencyClient) GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateResponse, error) {
	out := new(RateResponse)
	err := c.cc.Invoke(ctx, "/Currency/GetRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) SubscribeRates(ctx context.Context, opts ...grpc.CallOption) (Currency_SubscribeRatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Currency_serviceDesc.Streams[0], "/Currency/SubscribeRates", opts...)
	if err != nil {
		return nil, err
	}
	x := &currencySubscribeRatesClient{stream}
	return x, nil
}

type Currency_SubscribeRatesClient interface {
	Send(*RateRequest) error
	Recv() (*StreamingRateResponse, error)
	grpc.ClientStream
}

type currencySubscribeRatesClient struct {
	grpc.ClientStream
}

func (x *currencySubscribeRatesClient) Send(m *RateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *currencySubscribeRatesClient) Recv() (*StreamingRateResponse, error) {
	m := new(StreamingRateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CurrencyServer is the server API for Currency service.
type CurrencyServer interface {
	GetRate(context.Context, *RateRequest) (*RateResponse, error)
	SubscribeRates(Currency_SubscribeRatesServer) error
}

// UnimplementedCurrencyServer can be embedded to have forward compatible implementations.
type UnimplementedCurrencyServer struct {
}

func (*UnimplementedCurrencyServer) GetRate(ctx context.Context, req *RateRequest) (*RateResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method GetRate not implemented")
}
func (*UnimplementedCurrencyServer) SubscribeRates(srv Currency_SubscribeRatesServer) error {
	return status1.Errorf(codes.Unimplemented, "method SubscribeRates not implemented")
}

func RegisterCurrencyServer(s *grpc.Server, srv CurrencyServer) {
	s.RegisterService(&_Currency_serviceDesc, srv)
}

func _Currency_GetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).GetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Currency/GetRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).GetRate(ctx, req.(*RateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_SubscribeRates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CurrencyServer).SubscribeRates(&currencySubscribeRatesServer{stream})
}

type Currency_SubscribeRatesServer interface {
	Send(*StreamingRateResponse) error
	Recv() (*RateRequest, error)
	grpc.ServerStream
}

type currencySubscribeRatesServer struct {
	grpc.ServerStream
}

func (x *currencySubscribeRatesServer) Send(m *StreamingRateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *currencySubscribeRatesServer) Recv() (*RateRequest, error) {
	m := new(RateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Currency_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Currency",
	HandlerType: (*CurrencyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRate",
			Handler:    _Currency_GetRate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRates",
			Handler:       _Currency_SubscribeRates_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "currency.proto",
}
